# FLIP_C3 25.07 - Dash Import
# Voidbox Industries & Chloe Madison
# VDBX.io / @clomads
# CC-BY-SA 4.0
# Baseline ESPHome YAML for FLIP_C3
# 
# Hi Friend!
#
# This is where you can customize your FLIP-C3.
# We've broken up the basics into the packages below.
# We've left some starter configuration in place for you to edit.

substitutions:
  name: "flip-c3"
  friendly_name: "FLIP-C3"
  project_name: "vdbxio.FLIP-C3"
  project_version: "1.0.0"

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: true

packages:
  flipc3: github://vdbxio/esphome-configs/packages/flipc3-base.yaml@main
  wifi: github://vdbxio/esphome-configs/packages/flipc3-wifi.yaml@main
  leds: github://vdbxio/esphome-configs/packages/flipc3-leds.yaml@main
  # qaset: github://vdbxio/esphome-configs/packages/flipc3-qa.yaml@main
  # epever485: github://vdbxio/esphome-configs/packages/include/epever485.yaml@main
  #
  # Example packages - see github.com/vdbxio/esphome-configs for more info:
  # lsm303agr: github://vdbxio/esphome-configs/packages/parts/lsm303agr.yaml@main
  # victron: github://vdbxio/esphome-configs/packages/parts/victron-uart-dev.yaml@main
  # hoursCounter: github://vdbxio/esphome-configs/packages/include/hours-count.yaml@main
  # daly-bms: github://vdbxio/esphome-configs/packages/include/daly-bms.yaml@main

# WiFi credentials 
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

uart:
  - id: flipuart
    tx_pin: 21
    rx_pin: 20
    baud_rate: 9600

# Bluetooth proxy takes up a lot of space, use at your own risk
bluetooth_proxy:

# User button (Boot) on front of device 
binary_sensor:
  - platform: gpio
    id: boot_button
    pin: 
      number: 9
      #allow_other_uses: true
      #ignore_pin_validation_error: true
      mode:
        input: true
        pullup: true
      inverted: True
    name: Boot Button
