# PowerTool Pro 23.02-working
# Voidbox Industries & Chloe Madison
# VDBX.io / @clomads
# CC-BY-SA 4.0
# Visit wiki.VDBX.io for more information
# 0x:03:4d
# 0x034D

substitutions:
  name: pwrtool500
  friendly_name: "PwrTool500"
  project_name: "vdbxio.PwrTool500"
  project_version: "0.9.8"
  package_git: "github://vdbxio/esphome-configs/pwrtool500.yaml@main"

packages:
  flipc3: !include packages/flipc3-base.yaml
  wifi: !include packages/flipc3-wifi.yaml
  dash: !include packages/dash-import.yaml
  shtc3: !include packages/parts/env_shtcx.yaml
  leds: !include packages/flipc3-leds.yaml
  ina2xx: !include  {file: "packages/parts/ina2xx-dev.yaml", vars: {address: 0x40}}
  ina2xx-soc: !include packages/parts/ina2xx-soc.yaml
  qaset: !include packages/flipc3-qa.yaml
  # ble_server: !include packages/include/pt_ble_server.yaml
  # ina237: !include packages/parts/shunt_ina237.yaml
  # uart: !include packages/flipc3-uart.yaml
  # switchset: !include  {file: "packages/flip-switch4.yaml", vars: {address: 0x20, entid: swset1 }}
  # shunt9611: !include  {file: "packages/parts/shunt9611.yaml", vars: {address: 0x70, entid: shunt1, interval: 1s }}
  # hoursCounter: !include  {file: "packages/include/hours-count.yaml", vars: { entid: counter1 }}

# TODO
# Tie button to switch or dimmable w/ config option
# State of charge calculation
# ESPNow wireless display

output:
  - platform: ledc
    id: gpio_7
    pin: 
      number: 7
      inverted: False
      # allow_other_uses: true
      
light:
  - platform: monochromatic
    name: "PwrTool MOS Dimmable"
    disabled_by_default: True
    output: gpio_7

switch:
  - platform: output
    name: "PwrTool MOS Switch"
    output: gpio_7

time:
  - platform: homeassistant
    id: ha_time


# esp32_ble_server:
#   manufacturer: "VDBX.io"
#   model: "PwrTool 500"
#   appearance: 0x01E # Generic Power Device
#   manufacturer_data: [0x4C, 0, 0x23, 77, 0xF0 ]
#   on_connect:
#     - lambda: |-
#         ESP_LOGD("BLE", "Connection from %d", id);
#   on_disconnect:
#     - lambda: |-
#         ESP_LOGD("BLE", "Disconnection from %d", id);
#   services:
#     - uuid: 0000fff1-0000-1000-8000-00805f9b34fb
#       characteristics:
#         - uuid: 0000fff2-0000-1000-8000-00805f9b34fb
#           description: "Active Power"
#           read: true
#           value: "0.00"
#         - uuid: 0x2A19
#           id: battery_level
#           read: true
#           value: "100"
#         - uuid: 0x2AE0
#           id: average_current
#           read: true
#           value: "42.0"
#         - uuid: 0x2AE1
#           id: average_voltage
#           read: true
#           value: "25.4"
#         - uuid: 0x2B05
#           id: power
#           read: true
#           value: "55.2"
