# INA2XX 24.06-dev for PwrTool 500
# Voidbox Industries & Chloe Madison
# VDBX.io / @clomads
# CC-BY-SA 4.0
# 
# ina2xx: !include  {file: "packages/parts/ina2xx.yaml", vars: {address: 0x40}}


switch:
  - platform: template
    name: "Invert"
    id: invert
    restore_mode: RESTORE_DEFAULT_OFF
    optimistic: true
    entity_category: config

button:
  - platform: template
    name: Offset - Set
    id: zero_offset
    entity_category: config
    icon: "mdi:circle"
    on_press:
      - logger.log: "Setting Offset"
      - number.set:
          id: offsetI_num
          value: !lambda 'return id(rawI).raw_state;'
      - logger.log:
          format: "Current - %.1f / Power - %.1f"
          args: [ 'id(offsetI_num).state', 'id(offsetP_calc).state' ]
  - platform: template
    name: Offset - Clear
    id: clear_offset
    entity_category: config
    icon: "mdi:circle"
    on_press:
      - logger.log: "Clearing Offset"
      - number.set:
          id: offsetI_num
          value: 0.0
      - logger.log:
          format: "Current - %.1f / Power - %.1f"
          args: [ 'id(offsetI_num).state', 'id(offsetP_calc).state' ]





sensor:
  - platform: ina2xx_i2c
    id: ina23x
    address: ${address} # default: 0x40
    shunt_resistance: 0.00015 ohm
    model: INA238
    max_current: 500 A
    adc_range: 0
    adc_time: 4120 us
    adc_averaging: 128
    update_interval: 100ms
    # For 228/229:
    # energy: "Energy - Raw"
    # energy_joules: "Energy Joules - Raw"
    # charge: "Charge - Raw"
    # charge_coulombs: "Charge Coul - Raw"
    shunt_voltage:
      name: "Shunt - Voltage"
      device_class: "voltage"
      unit_of_measurement: "mV"
      accuracy_decimals: 3
      disabled_by_default: True
    bus_voltage:
      name: "Bus - Voltage"
      id: rawV
      accuracy_decimals: 3
    current:
      name: "Bus - Current"
      id: rawI
      accuracy_decimals: 2
      filters:
      - lambda: !lambda |-
          if (id(invert).state) return {x * -1};
          return x;
      - lambda: !lambda 'return x + id(offsetI_num).state;'
    power:
      name: "Bus - Power"
      id: rawP
      accuracy_decimals: 2
      filters:
      - lambda: !lambda |-
          if (id(invert).state) return {x * -1};
          return x;
      - lambda: !lambda 'return x + id(offsetP_calc).state;'
    temperature:
      name: "Temperature - Shunt"
      accuracy_decimals: 2

  - platform: template
    id: offsetP_calc
    name: "Offset - Power"
    lambda: !lambda 'return id(offsetI_num).state * id(rawV).state;'
    device_class: "power"
    unit_of_measurement: "W"
    entity_category: diagnostic
    update_interval: 1s
    on_value:
      - logger.log:
          format: "Power Offset set to %.1f"
          args: [ 'id(offsetP_calc).state' ]
number:
  - platform: template
    id: offsetI_num
    name: "Offset - Current"
    initial_value: 0.00
    min_value: -500.00
    max_value: 500.00
    step: 0.01
    optimistic: true
    restore_value: yes
    device_class: "current"
    unit_of_measurement: "A"
    entity_category: config
    on_value:
      - logger.log:
          format: "Current Offset set to %.1f"
          args: [ 'id(offsetI_num).state' ]



      












