substitutions:
  entid: counter1

globals:
  - id: ${entid}_hours
    type: float
    restore_value: yes
 
#Increment number by 0.1 every 6 minutes in global 
#this seems to be generating a ~0.0001 drift
interval:
  - interval: 6min
    then:
      - lambda: |-
         id(${entid}_hours) += 0.1; 
         id(${entid}_hours_num).publish_state(id(${entid}_hours));
         ESP_LOGD("main", "Generator Hours: %.1f", id(${entid}_hours));

number:
  - platform: template
    name: "Hours Counter"
    id: ${entid}_hours_num
    optimistic: true
    min_value: 0
    max_value: 100000
    step: 0.1
    

    